CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE,
  password TEXT,
  pfp TEXT DEFAULT 'https://i.imgur.com/0y8Ftya.png',
  status TEXT DEFAULT 'offline'
);

CREATE TABLE IF NOT EXISTS friends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  requester INTEGER,
  receiver INTEGER,
  status TEXT,
  FOREIGN KEY(requester) REFERENCES users(id),
  FOREIGN KEY(receiver) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS dms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user1 INTEGER,
  user2 INTEGER
);

CREATE TABLE IF NOT EXISTS rooms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  roomId INTEGER,
  dmId INTEGER,
  sender INTEGER,
  content TEXT,
  timestamp INTEGER,
  FOREIGN KEY(sender) REFERENCES users(id)
);
